############# CORE #############
#auth:
#  reset_admin_password: true

mqtt:
  enabled: true
  host: 192.168.179.12
  port: 1883
  user: mqtt_user
  password: pietro96X
  topic_prefix: frigate

tls:
  enabled: false

database:
  path: /db/frigate.db

birdseye:
  enabled: false

semantic_search:
  enabled: true
  reindex: false
  model_size: small

detectors:
  openvino:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

snapshots:
  enabled: false

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 0
    mode: all

  alerts:
    pre_capture: 2
    post_capture: 2
    retain:
      days: 0
      mode: motion

  detections:
    pre_capture: 2
    post_capture: 2
    retain:
      days: 0
      mode: motion

version: 0.15-1

############# DETECTIONS #############

objects:
  track:
    - person

  ############# GO2RTC with WEBRTC #############
go2rtc:
  webrtc:
    candidates:
      - 192.168.179.13:8555
      - stun:8555
  streams:

### CAMPANELLO ###
    Campanello_Main:
      - ffmpeg:https://192.168.100.83/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=pietro96X#audio=copy#video=copy#audio=opus
      - rtsp://admin:pietro96X@192.168.100.83/Preview_01_main
    Campanello_Sub:
      - rtsp://admin:pietro96X@192.168.100.83/Preview_01_sub
    Campanello_All:
      - ffmpeg:https://192.168.100.83/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=pietro96X#audio=copy#video=copy#audio=opus
      - rtsp://admin:pietro96X@192.168.100.83/Preview_01_sub

### STUDIO ###
    Studio_Main:
      - rtsp://rstpadm:pietro96@192.168.100.90/stream1
      - ffmpeg:Studio_Main#audio=aac

### CAM1 ###
    CAM1_Main:
      - rtsp://admin:pietro96X@192.168.100.91/Streaming/channels/101
      - ffmpeg:CAM1_Main#audio=aac
    CAM1_Sub:
      - rtsp://admin:pietro96X@192.168.100.91/Streaming/channels/102

### CAM2 ###
    CAM2_Main:
      - rtsp://admin:pietro96X@192.168.100.92/Streaming/channels/101
      - ffmpeg:CAM2_Main#audio=aac
    CAM2_Sub:
      - rtsp://admin:pietro96X@192.168.100.92/Streaming/channels/102

### CAM3 ###
    CAM3_Main:
      - rtsp://admin:pietro96X@192.168.100.93/Streaming/channels/101
      - ffmpeg:CAM3_Main#audio=aac
    CAM3_Sub:
      - rtsp://admin:pietro96X@192.168.100.93/Streaming/channels/102

### CAM4 ###
    CAM4_Main:
      - rtsp://admin:pietro96X@192.168.100.94/Streaming/channels/101
      - ffmpeg:CAM4_Main#audio=aac
    CAM4_Sub:
      - rtsp://admin:pietro96X@192.168.100.94/Streaming/channels/102

############# CAMERE #############
cameras:

### CAMPANELLO ###
  Campanello:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Campanello_Main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Campanello_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: Campanello_Main
    detect:
      enabled: true
      fps: 1

### STUDIO ###
  Studio:
    enabled: true
    onvif:
      host: 192.168.100.90
      port: 2020
      user: rstpadm
      password: pietro96
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Studio_Main
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: Studio_Main
    detect:
      enabled: true
      fps: 1

### CAM1 ###
  CAM1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM1_Main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM1_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: CAM1_Main
    detect:
      enabled: true
      fps: 1

### CAM2 ###
  CAM2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM2_Main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM2_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: CAM2_Main
    detect:
      enabled: true
      fps: 1

### CAM3 ###
  CAM3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM3_Main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM3_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: CAM3_Main
    detect:
      enabled: true
      fps: 1

### CAM4 ###
  CAM4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM4_Main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM4_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: CAM4_Main
    detect:
      enabled: true
      fps: 1
