############# CORE #############
#auth:
#  reset_admin_password: true

mqtt:
  enabled: true
  host: 192.168.100.99
  port: 1883
  user: mqtt_user
  password: pietro96X
  topic_prefix: frigate

tls:
  enabled: false

database:
  path: /db/frigate.db

birdseye:
  enabled: false

snapshots:
  enabled: true
  clean_copy: true

semantic_search:
  enabled: true
  reindex: false
  model_size: small

detectors:
  openvino:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detect:
  enabled: true

record:
  enabled: true
  sync_recordings: true
  retain:
    days: 3
    mode: all

  alerts:
    pre_capture: 2
    post_capture: 2
    retain:
      days: 3
      mode: motion

  detections:
    pre_capture: 2
    post_capture: 2
    retain:
      days: 30
      mode: motion

version: 0.16-0

############# DETECTIONS #############

objects:
  track:
    - person
    
  ############# GO2RTC with WEBRTC #############
go2rtc:
  webrtc:
    candidates:
      - 192.168.179.13:8555
      - stun:8555
  streams:

### CAMPANELLO ###
    Campanello_Main:
      - rtsp://admin:pietro96X@192.168.100.83/Preview_01_main
      - ffmpeg:camera.Campanello_Main#audio=opus#audio=copy
    Campanello_Sub:
      - rtsp://admin:pietro96X@192.168.100.83/Preview_01_sub
    Campanello_All:
      - rtsp://admin:pietro96X@192.168.100.83/Preview_01_sub
      - ffmpeg:camera.Campanello_All#audio=opus#audio=copy

### CAM1 ###
    CAM1_Main:
      - rtsp://admin:pietro96X@192.168.100.91/Streaming/channels/101
      - ffmpeg:CAM1_Main#audio=aac
    CAM1_Sub:
      - rtsp://admin:pietro96X@192.168.100.91/Streaming/channels/102

############# CAMERE #############
cameras:

### CAMPANELLO ###
  Campanello:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Campanello_Main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Campanello_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
      fps: 1

### CAM1 ###
  CAM1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/CAM1_Main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/CAM1_Sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true
      fps: 1
    zones:
      CAM1-Zona_Cancello:
        coordinates: 
          0.401,0.446,0.492,0.454,0.602,0.572,0.6,0.603,0.933,0.996,0.376,0.999,0.444,0.956,0.425,0.697,0.353,0.455
        loitering_time: 0
    motion: {}
    objects:
      mask: 
        0.492,0.454,0.956,0.415,0.956,0.26,0.997,0.269,1,1,0.93,0.991,0.599,0.606,0.6,0.571
